if not (string.find(Tracker.ActiveVariantUID, "items_only")) then
    Tracker:AddMaps("maps/maps.json")
    Tracker:AddLocations("locations/overworld.json")
    Tracker:AddLocations("locations/dungeons/dws/map.json")
    Tracker:AddLocations("locations/dungeons/dws/n.map.json")
    Tracker:AddLocations("locations/dungeons/cof/map.json")
    Tracker:AddLocations("locations/dungeons/cof/n.map.json")
    Tracker:AddLocations("locations/dungeons/cof/r.map.json")
    Tracker:AddLocations("locations/dungeons/fow/map.json")
    Tracker:AddLocations("locations/dungeons/fow/n.map.json")
    Tracker:AddLocations("locations/dungeons/fow/r.map.json")
    Tracker:AddLocations("locations/dungeons/fow/o.map.json")
    Tracker:AddLocations("locations/dungeons/fow/or.map.json")
    Tracker:AddLocations("locations/dungeons/tod/map.json")
    Tracker:AddLocations("locations/dungeons/tod/n.map.json")
    Tracker:AddLocations("locations/dungeons/tod/r.map.json")
    Tracker:AddLocations("locations/dungeons/tod/o.map.json")
    Tracker:AddLocations("locations/dungeons/tod/or.map.json")
    Tracker:AddLocations("locations/dungeons/rc/map.json")
    Tracker:AddLocations("locations/dungeons/rc/n.map.json")
    Tracker:AddLocations("locations/dungeons/pow/map.json")
    Tracker:AddLocations("locations/dungeons/pow/n.map.json")
    Tracker:AddLocations("locations/dungeons/pow/r.map.json")
    Tracker:AddLocations("locations/dungeons/dhc/map.json")
    Tracker:AddLocations("locations/dungeons/dhc/n.map.json")
    -- Tracker:AddLocations("locations/fusion.json")
end