ROOM_FLAG_MAPPING = {
    ["00"] = {[0] = {"Overworld"}},
    ["10"] = {[0] = {"Melari's Mines"}},
    ["48"] = {[0] = {"Maps Dungeons", "Deepwood Shrine"}},
    ["49"] = {[0] = {"Maps Dungeons", "Deepwood Shrine"}},
    ["50"] = {[0] = {"Maps Dungeons", "Cave of Flames"}},
    ["51"] = {[0] = {"Maps Dungeons", "Cave of Flames"}},
    ["18"] = {[0] = {"Maps Dungeons", "Fortress of Winds"}},
    ["58"] = {[0] = {"Maps Dungeons", "Fortress of Winds"}},
    ["59"] = {[0] = {"Maps Dungeons", "Fortress Of Winds"}},
    ["5a"] = {[0] = {"Maps Dungeons", "Fortress Of Winds"}},
    ["60"] = {[0] = {"Maps Dungeons", "Temple of Droplets"}},
    ["68"] = {[0] = {"Maps Dungeons", "Royal Crypt"}},
    ["70"] = {[0] = {"Maps Dungeons", "Palace of Winds"}},
    ["71"] = {[0] = {"Maps Dungeons", "Palace of Winds"}},
    ["88"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
    ["89"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
    ["8a"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
    ["8b"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
    ["8c"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
    ["8d"] = {[0] = {"Maps Dungeons", "Dark Hyrule Castle"}},
}
ROOM_FLAG_MAPPING_SPEC={
    ["092c"] = {[0] = {"Maps Dungeons", "Fortress Of Winds"}},
    ["0a2c"] = {[0] = {"Maps Dungeons", "Fortress Of Winds"}},
 -- deepwood shrine
    -- ["0048"] = {[0] = {"Maps Dungeons", "Deepwood Shrine","B1"}},

 -- cave of flame
    -- ["0050"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0150"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0250"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0350"] = {[0] = {"Maps Dungeons", "Cave of Flames","1F"}},
    -- ["0450"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0550"] = {[0] = {"Maps Dungeons", "Cave of Flames","1F"}},
    -- ["0650"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0750"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0850"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["0950"] = {[0] = {"Maps Dungeons", "Cave of Flames","B1"}},
    -- ["1050"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["1150"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["1250"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["1350"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["1450"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["1550"] = {[0] = {"Maps Dungeons", "Cave of Flames","1F"}},
    -- ["1650"] = {[0] = {"Maps Dungeons", "Cave of Flames","1F"}},
    -- ["1750"] = {[0] = {"Maps Dungeons", "Cave of Flames","B2"}},
    -- ["0051"] = {[0] = {"Maps Dungeons", "Cave of Flames","B3"}},
  -- droplet
    -- ["0060"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0160"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0260"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0360"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0460"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0560"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0660"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0760"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0860"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0960"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0a60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0b60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0c60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0d60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0e60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["0f60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["1060"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B1"}},
    -- ["1160"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B3"}},
    -- ["2060"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2160"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2260"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2360"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2460"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2560"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2660"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2760"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2860"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2960"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2a60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2b60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2c60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2d60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2e60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["2f60"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3060"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3160"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3260"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3360"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3460"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3560"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},
    -- ["3660"] = {[0] = {"Maps Dungeons", "Temple of Droplets","B2"}},

}