setting_preset_data={}
setting_preset_data_cache=-1
setting_preset_data["Weekly2022"]={}
setting_preset_data["Weekly2022"]["dhc_closed"]=0
setting_preset_data["Weekly2022"]["dungeons"]=0
setting_preset_data["Weekly2022"]["sword0Needed"]=5
setting_preset_data["Weekly2022"]["element4Needed"]=4
setting_preset_data["Weekly2022"]["cucco_none"]=1
setting_preset_data["Weekly2022"]["goron_none"]=0
setting_preset_data["Weekly2022"]["hp_shuffle"]=1
setting_preset_data["Weekly2022"]["rupees_off"]=1
setting_preset_data["Weekly2022"]["specialpot_off"]=1
setting_preset_data["Weekly2022"]["digging_off"]=1
setting_preset_data["Weekly2022"]["underwater_off"]=1
setting_preset_data["Weekly2022"]["golden_enemy_off"]=0
setting_preset_data["Weekly2022"]["ped_items_off"]=0
setting_preset_data["Weekly2022"]["openworld_off"]=0
setting_preset_data["Weekly2022"]["dungeonser_off"]=0
setting_preset_data["Weekly2022"]["dws_none"]=0
setting_preset_data["Weekly2022"]["cof_none"]=0
setting_preset_data["Weekly2022"]["fow_none"]=0
setting_preset_data["Weekly2022"]["tod_none"]=0
setting_preset_data["Weekly2022"]["crypt_none"]=0
setting_preset_data["Weekly2022"]["pow_none"]=0
setting_preset_data["Weekly2022"]["dhc_none"]=0
setting_preset_data["Weekly2022"]["fusiongold_removed"]=1
setting_preset_data["Weekly2022"]["fusionred_removed"]=2
setting_preset_data["Weekly2022"]["fusionblue_removed"]=2
setting_preset_data["Weekly2022"]["fusiongreen_removed"]=2
setting_preset_data["Weekly2022"]["crenelwindcrest_no"]=0
setting_preset_data["Weekly2022"]["fallswindcrest_no"]=0
setting_preset_data["Weekly2022"]["cloudwindcrest_no"]=0
setting_preset_data["Weekly2022"]["swampwindcrest_no"]=0
setting_preset_data["Weekly2022"]["shfwindcrest_no"]=0
setting_preset_data["Weekly2022"]["minishwindcrest_no"]=0
setting_preset_data["Weekly2022"]["dws_warps_none"]=0
setting_preset_data["Weekly2022"]["cof_warps_none"]=0
setting_preset_data["Weekly2022"]["fow_warps_none"]=0
setting_preset_data["Weekly2022"]["tod_warps_none"]=0
setting_preset_data["Weekly2022"]["pow_warps_none"]=0
setting_preset_data["Weekly2022"]["dhc_warps_none"]=0
setting_preset_data["Weekly2022"]["grabbable_none"]=0
setting_preset_data["Weekly2022"]["weaponsbombs_no"]=1
setting_preset_data["Weekly2022"]["weaponsbow_no"]=1
setting_preset_data["Weekly2022"]["weaponsgust_no"]=0
setting_preset_data["Weekly2022"]["weaponslamp_no"]=0
setting_preset_data["Weekly2022"]["blowdust_off"]=1
setting_preset_data["Weekly2022"]["crenelmushroom_off"]=1
setting_preset_data["Weekly2022"]["lightarrowbreak_off"]=1
setting_preset_data["Weekly2022"]["bobombs_off"]=1
setting_preset_data["Weekly2022"]["likelike_off"]=1
setting_preset_data["Weekly2022"]["guardskip_off"]=0
setting_preset_data["Weekly2022"]["crenelbeam_off"]=1
setting_preset_data["Weekly2022"]["downstrikebeetle_off"]=1
setting_preset_data["Weekly2022"]["darkrooms_off"]=0
setting_preset_data["Weekly2022"]["capeextension_off"]=1
setting_preset_data["Weekly2022"]["lakeminish_off"]=0
setting_preset_data["Weekly2022"]["cabinswim_off"]=1
setting_preset_data["Weekly2022"]["cloudskill_off"]=1
setting_preset_data["Weekly2022"]["powjump_off"]=0
setting_preset_data["Weekly2022"]["powpotpuzzleool_off"]=0
setting_preset_data["Weekly2022"]["dhccanonhit_off"]=0
setting_preset_data["Weekly2022"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Weekly2022"]["dhcswitchhit_off"]=0
setting_preset_data["Weekly2022"]["fowpot_off"]=0
setting_preset_data["Weekly2022"]["goron_eu"]=0
setting_preset_data["Weekly2022"]["small_key_none"]=2
setting_preset_data["Weekly2022"]["big_key_none"]=2
setting_preset_data["Weekly2022"]["fusiongoldcombined"]=false
setting_preset_data["Weekly2022"]["fusionredcombined"]=false
setting_preset_data["Weekly2022"]["fusiongreencombined"]=false
setting_preset_data["Weekly2022"]["fusionbluecombined"]=false
setting_preset_data["Weekly2022"]["progressiveitems"]=true
setting_preset_data["Weekly2022"]["figurine_option"]=0
setting_preset_data["Beginner"]={}
setting_preset_data["Beginner"]["dhc_closed"]=1
setting_preset_data["Beginner"]["dungeons"]=0
setting_preset_data["Beginner"]["sword0Needed"]=5
setting_preset_data["Beginner"]["element4Needed"]=4
setting_preset_data["Beginner"]["cucco_none"]=0
setting_preset_data["Beginner"]["goron_none"]=0
setting_preset_data["Beginner"]["hp_shuffle"]=1
setting_preset_data["Beginner"]["rupees_off"]=0
setting_preset_data["Beginner"]["specialpot_off"]=0
setting_preset_data["Beginner"]["digging_off"]=0
setting_preset_data["Beginner"]["underwater_off"]=0
setting_preset_data["Beginner"]["golden_enemy_off"]=0
setting_preset_data["Beginner"]["ped_items_off"]=0
setting_preset_data["Beginner"]["openworld_off"]=0
setting_preset_data["Beginner"]["dungeonser_off"]=0
setting_preset_data["Beginner"]["dws_none"]=0
setting_preset_data["Beginner"]["cof_none"]=0
setting_preset_data["Beginner"]["fow_none"]=0
setting_preset_data["Beginner"]["tod_none"]=0
setting_preset_data["Beginner"]["crypt_none"]=0
setting_preset_data["Beginner"]["pow_none"]=0
setting_preset_data["Beginner"]["dhc_none"]=0
setting_preset_data["Beginner"]["fusiongold_removed"]=0
setting_preset_data["Beginner"]["fusionred_removed"]=0
setting_preset_data["Beginner"]["fusionblue_removed"]=0
setting_preset_data["Beginner"]["fusiongreen_removed"]=0
setting_preset_data["Beginner"]["crenelwindcrest_no"]=0
setting_preset_data["Beginner"]["fallswindcrest_no"]=0
setting_preset_data["Beginner"]["cloudwindcrest_no"]=0
setting_preset_data["Beginner"]["swampwindcrest_no"]=0
setting_preset_data["Beginner"]["shfwindcrest_no"]=0
setting_preset_data["Beginner"]["minishwindcrest_no"]=0
setting_preset_data["Beginner"]["dws_warps_none"]=0
setting_preset_data["Beginner"]["cof_warps_none"]=0
setting_preset_data["Beginner"]["fow_warps_none"]=0
setting_preset_data["Beginner"]["tod_warps_none"]=0
setting_preset_data["Beginner"]["pow_warps_none"]=0
setting_preset_data["Beginner"]["dhc_warps_none"]=0
setting_preset_data["Beginner"]["grabbable_none"]=0
setting_preset_data["Beginner"]["weaponsbombs_no"]=0
setting_preset_data["Beginner"]["weaponsbow_no"]=0
setting_preset_data["Beginner"]["weaponsgust_no"]=0
setting_preset_data["Beginner"]["weaponslamp_no"]=0
setting_preset_data["Beginner"]["blowdust_off"]=0
setting_preset_data["Beginner"]["crenelmushroom_off"]=0
setting_preset_data["Beginner"]["lightarrowbreak_off"]=0
setting_preset_data["Beginner"]["bobombs_off"]=0
setting_preset_data["Beginner"]["likelike_off"]=0
setting_preset_data["Beginner"]["guardskip_off"]=0
setting_preset_data["Beginner"]["crenelbeam_off"]=0
setting_preset_data["Beginner"]["downstrikebeetle_off"]=0
setting_preset_data["Beginner"]["darkrooms_off"]=0
setting_preset_data["Beginner"]["capeextension_off"]=0
setting_preset_data["Beginner"]["lakeminish_off"]=0
setting_preset_data["Beginner"]["cabinswim_off"]=0
setting_preset_data["Beginner"]["cloudskill_off"]=0
setting_preset_data["Beginner"]["powjump_off"]=0
setting_preset_data["Beginner"]["powpotpuzzleool_off"]=0
setting_preset_data["Beginner"]["dhccanonhit_off"]=0
setting_preset_data["Beginner"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Beginner"]["dhcswitchhit_off"]=0
setting_preset_data["Beginner"]["fowpot_off"]=0
setting_preset_data["Beginner"]["goron_eu"]=0
setting_preset_data["Beginner"]["small_key_none"]=0
setting_preset_data["Beginner"]["big_key_none"]=0
setting_preset_data["Beginner"]["fusiongoldcombined"]=false
setting_preset_data["Beginner"]["fusionredcombined"]=false
setting_preset_data["Beginner"]["fusiongreencombined"]=false
setting_preset_data["Beginner"]["fusionbluecombined"]=false
setting_preset_data["Beginner"]["progressiveitems"]=true
setting_preset_data["Beginner"]["figurine_option"]=0
setting_preset_data["Intermediate"]={}
setting_preset_data["Intermediate"]["dhc_closed"]=1
setting_preset_data["Intermediate"]["dungeons"]=0
setting_preset_data["Intermediate"]["sword0Needed"]=5
setting_preset_data["Intermediate"]["element4Needed"]=4
setting_preset_data["Intermediate"]["cucco_none"]=0
setting_preset_data["Intermediate"]["goron_none"]=0
setting_preset_data["Intermediate"]["hp_shuffle"]=1
setting_preset_data["Intermediate"]["rupees_off"]=1
setting_preset_data["Intermediate"]["specialpot_off"]=0
setting_preset_data["Intermediate"]["digging_off"]=0
setting_preset_data["Intermediate"]["underwater_off"]=0
setting_preset_data["Intermediate"]["golden_enemy_off"]=0
setting_preset_data["Intermediate"]["ped_items_off"]=0
setting_preset_data["Intermediate"]["openworld_off"]=0
setting_preset_data["Intermediate"]["dungeonser_off"]=0
setting_preset_data["Intermediate"]["dws_none"]=0
setting_preset_data["Intermediate"]["cof_none"]=0
setting_preset_data["Intermediate"]["fow_none"]=0
setting_preset_data["Intermediate"]["tod_none"]=0
setting_preset_data["Intermediate"]["crypt_none"]=0
setting_preset_data["Intermediate"]["pow_none"]=0
setting_preset_data["Intermediate"]["dhc_none"]=0
setting_preset_data["Intermediate"]["fusiongold_removed"]=1
setting_preset_data["Intermediate"]["fusionred_removed"]=0
setting_preset_data["Intermediate"]["fusionblue_removed"]=0
setting_preset_data["Intermediate"]["fusiongreen_removed"]=0
setting_preset_data["Intermediate"]["crenelwindcrest_no"]=0
setting_preset_data["Intermediate"]["fallswindcrest_no"]=0
setting_preset_data["Intermediate"]["cloudwindcrest_no"]=0
setting_preset_data["Intermediate"]["swampwindcrest_no"]=0
setting_preset_data["Intermediate"]["shfwindcrest_no"]=0
setting_preset_data["Intermediate"]["minishwindcrest_no"]=0
setting_preset_data["Intermediate"]["dws_warps_none"]=0
setting_preset_data["Intermediate"]["cof_warps_none"]=0
setting_preset_data["Intermediate"]["fow_warps_none"]=0
setting_preset_data["Intermediate"]["tod_warps_none"]=0
setting_preset_data["Intermediate"]["pow_warps_none"]=0
setting_preset_data["Intermediate"]["dhc_warps_none"]=0
setting_preset_data["Intermediate"]["grabbable_none"]=0
setting_preset_data["Intermediate"]["weaponsbombs_no"]=0
setting_preset_data["Intermediate"]["weaponsbow_no"]=0
setting_preset_data["Intermediate"]["weaponsgust_no"]=0
setting_preset_data["Intermediate"]["weaponslamp_no"]=0
setting_preset_data["Intermediate"]["blowdust_off"]=0
setting_preset_data["Intermediate"]["crenelmushroom_off"]=0
setting_preset_data["Intermediate"]["lightarrowbreak_off"]=0
setting_preset_data["Intermediate"]["bobombs_off"]=0
setting_preset_data["Intermediate"]["likelike_off"]=0
setting_preset_data["Intermediate"]["guardskip_off"]=0
setting_preset_data["Intermediate"]["crenelbeam_off"]=0
setting_preset_data["Intermediate"]["downstrikebeetle_off"]=0
setting_preset_data["Intermediate"]["darkrooms_off"]=0
setting_preset_data["Intermediate"]["capeextension_off"]=0
setting_preset_data["Intermediate"]["lakeminish_off"]=0
setting_preset_data["Intermediate"]["cabinswim_off"]=0
setting_preset_data["Intermediate"]["cloudskill_off"]=0
setting_preset_data["Intermediate"]["powjump_off"]=0
setting_preset_data["Intermediate"]["powpotpuzzleool_off"]=0
setting_preset_data["Intermediate"]["dhccanonhit_off"]=0
setting_preset_data["Intermediate"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Intermediate"]["dhcswitchhit_off"]=0
setting_preset_data["Intermediate"]["fowpot_off"]=0
setting_preset_data["Intermediate"]["goron_eu"]=0
setting_preset_data["Intermediate"]["small_key_none"]=2
setting_preset_data["Intermediate"]["big_key_none"]=2
setting_preset_data["Intermediate"]["fusiongoldcombined"]=false
setting_preset_data["Intermediate"]["fusionredcombined"]=false
setting_preset_data["Intermediate"]["fusiongreencombined"]=false
setting_preset_data["Intermediate"]["fusionbluecombined"]=false
setting_preset_data["Intermediate"]["progressiveitems"]=true
setting_preset_data["Intermediate"]["figurine_option"]=0
setting_preset_data["Advanced"]={}
setting_preset_data["Advanced"]["dhc_closed"]=2
setting_preset_data["Advanced"]["dungeons"]=0
setting_preset_data["Advanced"]["sword0Needed"]=5
setting_preset_data["Advanced"]["element4Needed"]=4
setting_preset_data["Advanced"]["cucco_none"]=1
setting_preset_data["Advanced"]["goron_none"]=3
setting_preset_data["Advanced"]["hp_shuffle"]=1
setting_preset_data["Advanced"]["rupees_off"]=1
setting_preset_data["Advanced"]["specialpot_off"]=1
setting_preset_data["Advanced"]["digging_off"]=1
setting_preset_data["Advanced"]["underwater_off"]=1
setting_preset_data["Advanced"]["golden_enemy_off"]=1
setting_preset_data["Advanced"]["ped_items_off"]=1
setting_preset_data["Advanced"]["openworld_off"]=0
setting_preset_data["Advanced"]["dungeonser_off"]=1
setting_preset_data["Advanced"]["dws_none"]=0
setting_preset_data["Advanced"]["cof_none"]=0
setting_preset_data["Advanced"]["fow_none"]=0
setting_preset_data["Advanced"]["tod_none"]=0
setting_preset_data["Advanced"]["crypt_none"]=0
setting_preset_data["Advanced"]["pow_none"]=0
setting_preset_data["Advanced"]["dhc_none"]=0
setting_preset_data["Advanced"]["fusiongold_removed"]=1
setting_preset_data["Advanced"]["fusionred_removed"]=2
setting_preset_data["Advanced"]["fusionblue_removed"]=2
setting_preset_data["Advanced"]["fusiongreen_removed"]=2
setting_preset_data["Advanced"]["crenelwindcrest_no"]=0
setting_preset_data["Advanced"]["fallswindcrest_no"]=0
setting_preset_data["Advanced"]["cloudwindcrest_no"]=0
setting_preset_data["Advanced"]["swampwindcrest_no"]=0
setting_preset_data["Advanced"]["shfwindcrest_no"]=0
setting_preset_data["Advanced"]["minishwindcrest_no"]=0
setting_preset_data["Advanced"]["dws_warps_none"]=0
setting_preset_data["Advanced"]["cof_warps_none"]=0
setting_preset_data["Advanced"]["fow_warps_none"]=0
setting_preset_data["Advanced"]["tod_warps_none"]=2
setting_preset_data["Advanced"]["pow_warps_none"]=0
setting_preset_data["Advanced"]["dhc_warps_none"]=0
setting_preset_data["Advanced"]["grabbable_none"]=1
setting_preset_data["Advanced"]["weaponsbombs_no"]=1
setting_preset_data["Advanced"]["weaponsbow_no"]=1
setting_preset_data["Advanced"]["weaponsgust_no"]=1
setting_preset_data["Advanced"]["weaponslamp_no"]=1
setting_preset_data["Advanced"]["blowdust_off"]=1
setting_preset_data["Advanced"]["crenelmushroom_off"]=1
setting_preset_data["Advanced"]["lightarrowbreak_off"]=1
setting_preset_data["Advanced"]["bobombs_off"]=1
setting_preset_data["Advanced"]["likelike_off"]=1
setting_preset_data["Advanced"]["guardskip_off"]=0
setting_preset_data["Advanced"]["crenelbeam_off"]=0
setting_preset_data["Advanced"]["downstrikebeetle_off"]=0
setting_preset_data["Advanced"]["darkrooms_off"]=0
setting_preset_data["Advanced"]["capeextension_off"]=1
setting_preset_data["Advanced"]["lakeminish_off"]=0
setting_preset_data["Advanced"]["cabinswim_off"]=1
setting_preset_data["Advanced"]["cloudskill_off"]=1
setting_preset_data["Advanced"]["powjump_off"]=0
setting_preset_data["Advanced"]["powpotpuzzleool_off"]=0
setting_preset_data["Advanced"]["dhccanonhit_off"]=0
setting_preset_data["Advanced"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Advanced"]["dhcswitchhit_off"]=0
setting_preset_data["Advanced"]["fowpot_off"]=1
setting_preset_data["Advanced"]["goron_eu"]=0
setting_preset_data["Advanced"]["small_key_none"]=2
setting_preset_data["Advanced"]["big_key_none"]=2
setting_preset_data["Advanced"]["fusiongoldcombined"]=false
setting_preset_data["Advanced"]["fusionredcombined"]=false
setting_preset_data["Advanced"]["fusiongreencombined"]=false
setting_preset_data["Advanced"]["fusionbluecombined"]=false
setting_preset_data["Advanced"]["progressiveitems"]=true
setting_preset_data["Advanced"]["figurine_option"]=20
setting_preset_data["Expert"]={}
setting_preset_data["Expert"]["dhc_closed"]=3
setting_preset_data["Expert"]["dungeons"]=6
setting_preset_data["Expert"]["sword0Needed"]=5
setting_preset_data["Expert"]["element4Needed"]=4
setting_preset_data["Expert"]["cucco_none"]=10
setting_preset_data["Expert"]["goron_none"]=5
setting_preset_data["Expert"]["hp_shuffle"]=1
setting_preset_data["Expert"]["rupees_off"]=1
setting_preset_data["Expert"]["specialpot_off"]=1
setting_preset_data["Expert"]["digging_off"]=1
setting_preset_data["Expert"]["underwater_off"]=1
setting_preset_data["Expert"]["golden_enemy_off"]=1
setting_preset_data["Expert"]["ped_items_off"]=1
setting_preset_data["Expert"]["openworld_off"]=0
setting_preset_data["Expert"]["dungeonser_off"]=1
setting_preset_data["Expert"]["dws_none"]=0
setting_preset_data["Expert"]["cof_none"]=0
setting_preset_data["Expert"]["fow_none"]=0
setting_preset_data["Expert"]["tod_none"]=0
setting_preset_data["Expert"]["crypt_none"]=0
setting_preset_data["Expert"]["pow_none"]=0
setting_preset_data["Expert"]["dhc_none"]=0
setting_preset_data["Expert"]["fusiongold_removed"]=1
setting_preset_data["Expert"]["fusionred_removed"]=1
setting_preset_data["Expert"]["fusionblue_removed"]=1
setting_preset_data["Expert"]["fusiongreen_removed"]=1
setting_preset_data["Expert"]["crenelwindcrest_no"]=0
setting_preset_data["Expert"]["fallswindcrest_no"]=0
setting_preset_data["Expert"]["cloudwindcrest_no"]=0
setting_preset_data["Expert"]["swampwindcrest_no"]=0
setting_preset_data["Expert"]["shfwindcrest_no"]=0
setting_preset_data["Expert"]["minishwindcrest_no"]=0
setting_preset_data["Expert"]["dws_warps_none"]=0
setting_preset_data["Expert"]["cof_warps_none"]=0
setting_preset_data["Expert"]["fow_warps_none"]=0
setting_preset_data["Expert"]["tod_warps_none"]=0
setting_preset_data["Expert"]["pow_warps_none"]=0
setting_preset_data["Expert"]["dhc_warps_none"]=0
setting_preset_data["Expert"]["grabbable_none"]=2
setting_preset_data["Expert"]["weaponsbombs_no"]=2
setting_preset_data["Expert"]["weaponsbow_no"]=2
setting_preset_data["Expert"]["weaponsgust_no"]=1
setting_preset_data["Expert"]["weaponslamp_no"]=1
setting_preset_data["Expert"]["blowdust_off"]=1
setting_preset_data["Expert"]["crenelmushroom_off"]=1
setting_preset_data["Expert"]["lightarrowbreak_off"]=1
setting_preset_data["Expert"]["bobombs_off"]=1
setting_preset_data["Expert"]["likelike_off"]=1
setting_preset_data["Expert"]["guardskip_off"]=1
setting_preset_data["Expert"]["crenelbeam_off"]=1
setting_preset_data["Expert"]["downstrikebeetle_off"]=1
setting_preset_data["Expert"]["darkrooms_off"]=1
setting_preset_data["Expert"]["capeextension_off"]=1
setting_preset_data["Expert"]["lakeminish_off"]=1
setting_preset_data["Expert"]["cabinswim_off"]=1
setting_preset_data["Expert"]["cloudskill_off"]=10
setting_preset_data["Expert"]["powjump_off"]=1
setting_preset_data["Expert"]["powpotpuzzleool_off"]=1
setting_preset_data["Expert"]["dhccanonhit_off"]=1
setting_preset_data["Expert"]["dhcbladepuzzleshuffle_off"]=1
setting_preset_data["Expert"]["dhcswitchhit_off"]=1
setting_preset_data["Expert"]["fowpot_off"]=1
setting_preset_data["Expert"]["goron_eu"]=0
setting_preset_data["Expert"]["small_key_none"]=2
setting_preset_data["Expert"]["big_key_none"]=2
setting_preset_data["Expert"]["fusiongoldcombined"]=false
setting_preset_data["Expert"]["fusionredcombined"]=false
setting_preset_data["Expert"]["fusiongreencombined"]=false
setting_preset_data["Expert"]["fusionbluecombined"]=false
setting_preset_data["Expert"]["progressiveitems"]=false
setting_preset_data["Expert"]["figurine_option"]=1
setting_preset_data["Max Random"]={}
setting_preset_data["Max Random"]["dhc_closed"]=2
setting_preset_data["Max Random"]["dungeons"]=6
setting_preset_data["Max Random"]["sword0Needed"]=5
setting_preset_data["Max Random"]["element4Needed"]=4
setting_preset_data["Max Random"]["cucco_none"]=10
setting_preset_data["Max Random"]["goron_none"]=5
setting_preset_data["Max Random"]["hp_shuffle"]=1
setting_preset_data["Max Random"]["rupees_off"]=1
setting_preset_data["Max Random"]["specialpot_off"]=1
setting_preset_data["Max Random"]["digging_off"]=1
setting_preset_data["Max Random"]["underwater_off"]=1
setting_preset_data["Max Random"]["golden_enemy_off"]=1
setting_preset_data["Max Random"]["ped_items_off"]=1
setting_preset_data["Max Random"]["openworld_off"]=0
setting_preset_data["Max Random"]["dungeonser_off"]=0
setting_preset_data["Max Random"]["dws_none"]=0
setting_preset_data["Max Random"]["cof_none"]=0
setting_preset_data["Max Random"]["fow_none"]=0
setting_preset_data["Max Random"]["tod_none"]=0
setting_preset_data["Max Random"]["crypt_none"]=0
setting_preset_data["Max Random"]["pow_none"]=0
setting_preset_data["Max Random"]["dhc_none"]=0
setting_preset_data["Max Random"]["fusiongold_removed"]=1
setting_preset_data["Max Random"]["fusionred_removed"]=1
setting_preset_data["Max Random"]["fusionblue_removed"]=1
setting_preset_data["Max Random"]["fusiongreen_removed"]=1
setting_preset_data["Max Random"]["crenelwindcrest_no"]=1
setting_preset_data["Max Random"]["fallswindcrest_no"]=1
setting_preset_data["Max Random"]["cloudwindcrest_no"]=1
setting_preset_data["Max Random"]["swampwindcrest_no"]=1
setting_preset_data["Max Random"]["shfwindcrest_no"]=1
setting_preset_data["Max Random"]["minishwindcrest_no"]=1
setting_preset_data["Max Random"]["dws_warps_none"]=3
setting_preset_data["Max Random"]["cof_warps_none"]=3
setting_preset_data["Max Random"]["fow_warps_none"]=3
setting_preset_data["Max Random"]["tod_warps_none"]=3
setting_preset_data["Max Random"]["pow_warps_none"]=3
setting_preset_data["Max Random"]["dhc_warps_none"]=3
setting_preset_data["Max Random"]["grabbable_none"]=0
setting_preset_data["Max Random"]["weaponsbombs_no"]=1
setting_preset_data["Max Random"]["weaponsbow_no"]=1
setting_preset_data["Max Random"]["weaponsgust_no"]=1
setting_preset_data["Max Random"]["weaponslamp_no"]=1
setting_preset_data["Max Random"]["blowdust_off"]=1
setting_preset_data["Max Random"]["crenelmushroom_off"]=1
setting_preset_data["Max Random"]["lightarrowbreak_off"]=1
setting_preset_data["Max Random"]["bobombs_off"]=1
setting_preset_data["Max Random"]["likelike_off"]=1
setting_preset_data["Max Random"]["guardskip_off"]=0
setting_preset_data["Max Random"]["crenelbeam_off"]=0
setting_preset_data["Max Random"]["downstrikebeetle_off"]=0
setting_preset_data["Max Random"]["darkrooms_off"]=0
setting_preset_data["Max Random"]["capeextension_off"]=1
setting_preset_data["Max Random"]["lakeminish_off"]=0
setting_preset_data["Max Random"]["cabinswim_off"]=1
setting_preset_data["Max Random"]["cloudskill_off"]=1
setting_preset_data["Max Random"]["powjump_off"]=0
setting_preset_data["Max Random"]["powpotpuzzleool_off"]=0
setting_preset_data["Max Random"]["dhccanonhit_off"]=0
setting_preset_data["Max Random"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Max Random"]["dhcswitchhit_off"]=0
setting_preset_data["Max Random"]["fowpot_off"]=1
setting_preset_data["Max Random"]["goron_eu"]=0
setting_preset_data["Max Random"]["small_key_none"]=2
setting_preset_data["Max Random"]["big_key_none"]=2
setting_preset_data["Max Random"]["fusiongoldcombined"]=false
setting_preset_data["Max Random"]["fusionredcombined"]=false
setting_preset_data["Max Random"]["fusiongreencombined"]=false
setting_preset_data["Max Random"]["fusionbluecombined"]=false
setting_preset_data["Max Random"]["progressiveitems"]=true
setting_preset_data["Max Random"]["figurine_option"]=136
setting_preset_data["No Logic - Open World"]={}
setting_preset_data["No Logic - Open World"]["dhc_closed"]=2
setting_preset_data["No Logic - Open World"]["dungeons"]=0
setting_preset_data["No Logic - Open World"]["sword0Needed"]=5
setting_preset_data["No Logic - Open World"]["element4Needed"]=4
setting_preset_data["No Logic - Open World"]["cucco_none"]=0
setting_preset_data["No Logic - Open World"]["goron_none"]=1
setting_preset_data["No Logic - Open World"]["hp_shuffle"]=1
setting_preset_data["No Logic - Open World"]["rupees_off"]=1
setting_preset_data["No Logic - Open World"]["specialpot_off"]=1
setting_preset_data["No Logic - Open World"]["digging_off"]=1
setting_preset_data["No Logic - Open World"]["underwater_off"]=1
setting_preset_data["No Logic - Open World"]["golden_enemy_off"]=1
setting_preset_data["No Logic - Open World"]["ped_items_off"]=1
setting_preset_data["No Logic - Open World"]["openworld_off"]=1
setting_preset_data["No Logic - Open World"]["dungeonser_off"]=1
setting_preset_data["No Logic - Open World"]["dws_none"]=0
setting_preset_data["No Logic - Open World"]["cof_none"]=0
setting_preset_data["No Logic - Open World"]["fow_none"]=0
setting_preset_data["No Logic - Open World"]["tod_none"]=0
setting_preset_data["No Logic - Open World"]["crypt_none"]=0
setting_preset_data["No Logic - Open World"]["pow_none"]=0
setting_preset_data["No Logic - Open World"]["dhc_none"]=0
setting_preset_data["No Logic - Open World"]["fusiongold_removed"]=2
setting_preset_data["No Logic - Open World"]["fusionred_removed"]=2
setting_preset_data["No Logic - Open World"]["fusionblue_removed"]=2
setting_preset_data["No Logic - Open World"]["fusiongreen_removed"]=2
setting_preset_data["No Logic - Open World"]["crenelwindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["fallswindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["cloudwindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["swampwindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["shfwindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["minishwindcrest_no"]=1
setting_preset_data["No Logic - Open World"]["dws_warps_none"]=3
setting_preset_data["No Logic - Open World"]["cof_warps_none"]=3
setting_preset_data["No Logic - Open World"]["fow_warps_none"]=3
setting_preset_data["No Logic - Open World"]["tod_warps_none"]=3
setting_preset_data["No Logic - Open World"]["pow_warps_none"]=3
setting_preset_data["No Logic - Open World"]["dhc_warps_none"]=3
setting_preset_data["No Logic - Open World"]["grabbable_none"]=1
setting_preset_data["No Logic - Open World"]["weaponsbombs_no"]=0
setting_preset_data["No Logic - Open World"]["weaponsbow_no"]=0
setting_preset_data["No Logic - Open World"]["weaponsgust_no"]=0
setting_preset_data["No Logic - Open World"]["weaponslamp_no"]=0
setting_preset_data["No Logic - Open World"]["blowdust_off"]=0
setting_preset_data["No Logic - Open World"]["crenelmushroom_off"]=0
setting_preset_data["No Logic - Open World"]["lightarrowbreak_off"]=0
setting_preset_data["No Logic - Open World"]["bobombs_off"]=0
setting_preset_data["No Logic - Open World"]["likelike_off"]=0
setting_preset_data["No Logic - Open World"]["guardskip_off"]=0
setting_preset_data["No Logic - Open World"]["crenelbeam_off"]=0
setting_preset_data["No Logic - Open World"]["downstrikebeetle_off"]=0
setting_preset_data["No Logic - Open World"]["darkrooms_off"]=0
setting_preset_data["No Logic - Open World"]["capeextension_off"]=0
setting_preset_data["No Logic - Open World"]["lakeminish_off"]=0
setting_preset_data["No Logic - Open World"]["cabinswim_off"]=0
setting_preset_data["No Logic - Open World"]["cloudskill_off"]=0
setting_preset_data["No Logic - Open World"]["powjump_off"]=0
setting_preset_data["No Logic - Open World"]["powpotpuzzleool_off"]=0
setting_preset_data["No Logic - Open World"]["dhccanonhit_off"]=0
setting_preset_data["No Logic - Open World"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["No Logic - Open World"]["dhcswitchhit_off"]=0
setting_preset_data["No Logic - Open World"]["fowpot_off"]=0
setting_preset_data["No Logic - Open World"]["goron_eu"]=0
setting_preset_data["No Logic - Open World"]["small_key_none"]=0
setting_preset_data["No Logic - Open World"]["big_key_none"]=0
setting_preset_data["No Logic - Open World"]["fusiongoldcombined"]=false
setting_preset_data["No Logic - Open World"]["fusionredcombined"]=false
setting_preset_data["No Logic - Open World"]["fusiongreencombined"]=false
setting_preset_data["No Logic - Open World"]["fusionbluecombined"]=false
setting_preset_data["No Logic - Open World"]["progressiveitems"]=true
setting_preset_data["No Logic - Open World"]["figurine_option"]=0
setting_preset_data["Firerod"]={}
setting_preset_data["Firerod"]["dhc_closed"]=3
setting_preset_data["Firerod"]["dungeons"]=0
setting_preset_data["Firerod"]["sword0Needed"]=5
setting_preset_data["Firerod"]["element4Needed"]=4
setting_preset_data["Firerod"]["cucco_none"]=0
setting_preset_data["Firerod"]["goron_none"]=1
setting_preset_data["Firerod"]["hp_shuffle"]=1
setting_preset_data["Firerod"]["rupees_off"]=1
setting_preset_data["Firerod"]["specialpot_off"]=1
setting_preset_data["Firerod"]["digging_off"]=1
setting_preset_data["Firerod"]["underwater_off"]=0
setting_preset_data["Firerod"]["golden_enemy_off"]=0
setting_preset_data["Firerod"]["ped_items_off"]=1
setting_preset_data["Firerod"]["openworld_off"]=0
setting_preset_data["Firerod"]["dungeonser_off"]=1
setting_preset_data["Firerod"]["dws_none"]=0
setting_preset_data["Firerod"]["cof_none"]=0
setting_preset_data["Firerod"]["fow_none"]=0
setting_preset_data["Firerod"]["tod_none"]=0
setting_preset_data["Firerod"]["crypt_none"]=0
setting_preset_data["Firerod"]["pow_none"]=0
setting_preset_data["Firerod"]["dhc_none"]=0
setting_preset_data["Firerod"]["fusiongold_removed"]=1
setting_preset_data["Firerod"]["fusionred_removed"]=1
setting_preset_data["Firerod"]["fusionblue_removed"]=1
setting_preset_data["Firerod"]["fusiongreen_removed"]=1
setting_preset_data["Firerod"]["crenelwindcrest_no"]=0
setting_preset_data["Firerod"]["fallswindcrest_no"]=0
setting_preset_data["Firerod"]["cloudwindcrest_no"]=0
setting_preset_data["Firerod"]["swampwindcrest_no"]=0
setting_preset_data["Firerod"]["shfwindcrest_no"]=0
setting_preset_data["Firerod"]["minishwindcrest_no"]=0
setting_preset_data["Firerod"]["dws_warps_none"]=0
setting_preset_data["Firerod"]["cof_warps_none"]=0
setting_preset_data["Firerod"]["fow_warps_none"]=0
setting_preset_data["Firerod"]["tod_warps_none"]=0
setting_preset_data["Firerod"]["pow_warps_none"]=0
setting_preset_data["Firerod"]["dhc_warps_none"]=0
setting_preset_data["Firerod"]["grabbable_none"]=0
setting_preset_data["Firerod"]["weaponsbombs_no"]=0
setting_preset_data["Firerod"]["weaponsbow_no"]=0
setting_preset_data["Firerod"]["weaponsgust_no"]=0
setting_preset_data["Firerod"]["weaponslamp_no"]=0
setting_preset_data["Firerod"]["blowdust_off"]=0
setting_preset_data["Firerod"]["crenelmushroom_off"]=0
setting_preset_data["Firerod"]["lightarrowbreak_off"]=0
setting_preset_data["Firerod"]["bobombs_off"]=0
setting_preset_data["Firerod"]["likelike_off"]=0
setting_preset_data["Firerod"]["guardskip_off"]=0
setting_preset_data["Firerod"]["crenelbeam_off"]=0
setting_preset_data["Firerod"]["downstrikebeetle_off"]=0
setting_preset_data["Firerod"]["darkrooms_off"]=0
setting_preset_data["Firerod"]["capeextension_off"]=0
setting_preset_data["Firerod"]["lakeminish_off"]=0
setting_preset_data["Firerod"]["cabinswim_off"]=0
setting_preset_data["Firerod"]["cloudskill_off"]=0
setting_preset_data["Firerod"]["powjump_off"]=0
setting_preset_data["Firerod"]["powpotpuzzleool_off"]=0
setting_preset_data["Firerod"]["dhccanonhit_off"]=0
setting_preset_data["Firerod"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Firerod"]["dhcswitchhit_off"]=0
setting_preset_data["Firerod"]["fowpot_off"]=0
setting_preset_data["Firerod"]["goron_eu"]=0
setting_preset_data["Firerod"]["small_key_none"]=2
setting_preset_data["Firerod"]["big_key_none"]=2
setting_preset_data["Firerod"]["fusiongoldcombined"]=true
setting_preset_data["Firerod"]["fusionredcombined"]=true
setting_preset_data["Firerod"]["fusiongreencombined"]=true
setting_preset_data["Firerod"]["fusionbluecombined"]=true
setting_preset_data["Firerod"]["progressiveitems"]=true
setting_preset_data["Firerod"]["figurine_option"]=20
setting_preset_data["Firerod"]["dhc_closed"]=3
setting_preset_data["Firerod"]["dungeons"]=0
setting_preset_data["Firerod"]["sword0Needed"]=5
setting_preset_data["Firerod"]["element4Needed"]=4
setting_preset_data["Firerod"]["cucco_none"]=0
setting_preset_data["Firerod"]["goron_none"]=1
setting_preset_data["Firerod"]["hp_shuffle"]=1
setting_preset_data["Firerod"]["rupees_off"]=1
setting_preset_data["Firerod"]["specialpot_off"]=1
setting_preset_data["Firerod"]["digging_off"]=1
setting_preset_data["Firerod"]["underwater_off"]=0
setting_preset_data["Firerod"]["golden_enemy_off"]=0
setting_preset_data["Firerod"]["ped_items_off"]=1
setting_preset_data["Firerod"]["openworld_off"]=0
setting_preset_data["Firerod"]["dungeonser_off"]=1
setting_preset_data["Firerod"]["dws_none"]=0
setting_preset_data["Firerod"]["cof_none"]=0
setting_preset_data["Firerod"]["fow_none"]=0
setting_preset_data["Firerod"]["tod_none"]=0
setting_preset_data["Firerod"]["crypt_none"]=0
setting_preset_data["Firerod"]["pow_none"]=0
setting_preset_data["Firerod"]["dhc_none"]=0
setting_preset_data["Firerod"]["fusiongold_removed"]=1
setting_preset_data["Firerod"]["fusionred_removed"]=1
setting_preset_data["Firerod"]["fusionblue_removed"]=1
setting_preset_data["Firerod"]["fusiongreen_removed"]=1
setting_preset_data["Firerod"]["crenelwindcrest_no"]=0
setting_preset_data["Firerod"]["fallswindcrest_no"]=0
setting_preset_data["Firerod"]["cloudwindcrest_no"]=0
setting_preset_data["Firerod"]["swampwindcrest_no"]=0
setting_preset_data["Firerod"]["shfwindcrest_no"]=0
setting_preset_data["Firerod"]["minishwindcrest_no"]=0
setting_preset_data["Firerod"]["dws_warps_none"]=0
setting_preset_data["Firerod"]["cof_warps_none"]=0
setting_preset_data["Firerod"]["fow_warps_none"]=0
setting_preset_data["Firerod"]["tod_warps_none"]=0
setting_preset_data["Firerod"]["pow_warps_none"]=0
setting_preset_data["Firerod"]["dhc_warps_none"]=0
setting_preset_data["Firerod"]["grabbable_none"]=0
setting_preset_data["Firerod"]["weaponsbombs_no"]=0
setting_preset_data["Firerod"]["weaponsbow_no"]=0
setting_preset_data["Firerod"]["weaponsgust_no"]=0
setting_preset_data["Firerod"]["weaponslamp_no"]=0
setting_preset_data["Firerod"]["blowdust_off"]=0
setting_preset_data["Firerod"]["crenelmushroom_off"]=0
setting_preset_data["Firerod"]["lightarrowbreak_off"]=0
setting_preset_data["Firerod"]["bobombs_off"]=0
setting_preset_data["Firerod"]["likelike_off"]=0
setting_preset_data["Firerod"]["guardskip_off"]=0
setting_preset_data["Firerod"]["crenelbeam_off"]=0
setting_preset_data["Firerod"]["downstrikebeetle_off"]=0
setting_preset_data["Firerod"]["darkrooms_off"]=0
setting_preset_data["Firerod"]["capeextension_off"]=0
setting_preset_data["Firerod"]["lakeminish_off"]=0
setting_preset_data["Firerod"]["cabinswim_off"]=0
setting_preset_data["Firerod"]["cloudskill_off"]=0
setting_preset_data["Firerod"]["powjump_off"]=0
setting_preset_data["Firerod"]["powpotpuzzleool_off"]=0
setting_preset_data["Firerod"]["dhccanonhit_off"]=0
setting_preset_data["Firerod"]["dhcbladepuzzleshuffle_off"]=0
setting_preset_data["Firerod"]["dhcswitchhit_off"]=0
setting_preset_data["Firerod"]["fowpot_off"]=0
setting_preset_data["Firerod"]["goron_eu"]=0
setting_preset_data["Firerod"]["small_key_none"]=2
setting_preset_data["Firerod"]["big_key_none"]=2
setting_preset_data["Firerod"]["fusiongoldcombined"]=true
setting_preset_data["Firerod"]["fusionredcombined"]=true
setting_preset_data["Firerod"]["fusiongreencombined"]=true
setting_preset_data["Firerod"]["fusionbluecombined"]=true
setting_preset_data["Firerod"]["progressiveitems"]=true
setting_preset_data["Firerod"]["figurine_option"]=20