numero_preset=1
ScriptHost:LoadScript(ScriptPreset.."list/Beginner.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Intermediate.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Advanced.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Expert.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Max Random.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Weekly2023.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Tournament 4 Settings.lua")
ScriptHost:LoadScript(ScriptPreset.."list/No Logic Open World.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Firerod.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Funky Fusions.lua")
ScriptHost:LoadScript(ScriptPreset.."list/v0.1.0 Settings.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Figurine Hunt.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Regional Dungeon Items.lua")
ScriptHost:LoadScript(ScriptPreset.."list/Custom.lua")