name: Auto-format JSON

on:
  push:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  format-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Format all JSON files
        run: |
          find . -name "*.json" -not -path "./.git/*" | while read file; do
            echo "Formatting $file"
            jq . "$file" > tmp.json && mv tmp.json "$file"
          done

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-formatted JSON files"
            git push
          else
            echo "No changes to commit."
          fi
